import { Movie, Review, List, Report, UserProfile } from "./types";

export const mockMovies: Movie[] = [
  {
    id: "1",
    title: "The Midnight Chronicles",
    year: 2024,
    runtime: 142,
    posterUrl: "https://images.unsplash.com/photo-1762356121454-877acbd554bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb3ZpZSUyMHBvc3RlciUyMGNpbmVtYXxlbnwxfHx8fDE3NjI3NDk5ODB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    backdropUrl: "https://images.unsplash.com/photo-1762356121454-877acbd554bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb3ZpZSUyMHBvc3RlciUyMGNpbmVtYXxlbnwxfHx8fDE3NjI3NDk5ODB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    director: "Sarah Chen",
    cast: ["Michael Torres", "Emma Richardson", "David Kim"],
    genres: ["Action", "Thriller", "Sci-Fi"],
    synopsis: "In a dystopian future where time is currency, a rebel group fights against the corrupt Time Authority to restore freedom to society.",
    userRating: 4.5,
    criticScore: 85,
  },
  {
    id: "2",
    title: "Echoes of Tomorrow",
    year: 2024,
    runtime: 128,
    posterUrl: "https://images.unsplash.com/photo-1645808651017-c5e3018553c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhY3Rpb24lMjBtb3ZpZSUyMHNjZW5lfGVufDF8fHx8MTc2Mjc3NTczMnww&ixlib=rb-4.1.0&q=80&w=1080",
    backdropUrl: "https://images.unsplash.com/photo-1645808651017-c5e3018553c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhY3Rpb24lMjBtb3ZpZSUyMHNjZW5lfGVufDF8fHx8MTc2Mjc3NTczMnww&ixlib=rb-4.1.0&q=80&w=1080",
    director: "James Morrison",
    cast: ["Lisa Park", "Robert Chen", "Maria Garcia"],
    genres: ["Drama", "Mystery"],
    synopsis: "A detective must solve a series of mysterious disappearances that seem to be connected to quantum physics experiments.",
    userRating: 4.2,
    criticScore: 78,
  },
  {
    id: "3",
    title: "Shadows in the Rain",
    year: 2023,
    runtime: 156,
    posterUrl: "https://images.unsplash.com/photo-1517486518908-97a5f91b325f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkcmFtYSUyMGZpbG0lMjBzY2VuZXxlbnwxfHx8fDE3NjI3MDgyNTd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    backdropUrl: "https://images.unsplash.com/photo-1517486518908-97a5f91b325f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkcmFtYSUyMGZpbG0lMjBzY2VuZXxlbnwxfHx8fDE3NjI3MDgyNTd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    director: "Alexandra Novak",
    cast: ["Tom Anderson", "Sophie Laurent", "Kevin Wu"],
    genres: ["Drama", "Romance"],
    synopsis: "Two strangers meet during a rainstorm and discover they share a mysterious connection that transcends time.",
    userRating: 4.7,
    criticScore: 92,
  },
  {
    id: "4",
    title: "The Last Horizon",
    year: 2023,
    runtime: 134,
    posterUrl: "https://images.unsplash.com/photo-1595171694538-beb81da39d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aHJpbGxlciUyMGRhcmslMjBzY2VuZXxlbnwxfHx8fDE3NjI3OTQzOTl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    backdropUrl: "https://images.unsplash.com/photo-1595171694538-beb81da39d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aHJpbGxlciUyMGRhcmslMjBzY2VuZXxlbnwxfHx8fDE3NjI3OTQzOTl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    director: "Marcus Johnson",
    cast: ["Anna Schmidt", "Carlos Rivera", "Yuki Tanaka"],
    genres: ["Thriller", "Horror"],
    synopsis: "A group of astronauts on a deep space mission discover an abandoned alien vessel with a terrifying secret.",
    userRating: 4.0,
    criticScore: 72,
  },
  {
    id: "5",
    title: "Laughter in the Dark",
    year: 2024,
    runtime: 98,
    posterUrl: "https://images.unsplash.com/photo-1632522497086-583f8cfec267?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb21lZHklMjBmaWxtJTIwYnJpZ2h0fGVufDF8fHx8MTc2Mjc5NDM5OXww&ixlib=rb-4.1.0&q=80&w=1080",
    backdropUrl: "https://images.unsplash.com/photo-1632522497086-583f8cfec267?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb21lZHklMjBmaWxtJTIwYnJpZ2h0fGVufDF8fHx8MTc2Mjc5NDM5OXww&ixlib=rb-4.1.0&q=80&w=1080",
    director: "Rachel Green",
    cast: ["Chris Evans", "Jenny Lee", "Mike Ross"],
    genres: ["Comedy", "Romance"],
    synopsis: "A comedy writer struggling with writers block accidentally creates the perfect rom-com scenario in real life.",
    userRating: 3.8,
    criticScore: 68,
  },
  {
    id: "6",
    title: "The Forgotten Realm",
    year: 2023,
    runtime: 168,
    posterUrl: "https://images.unsplash.com/photo-1551536637-f5f1984f1398?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob3Jyb3IlMjBkYXJrJTIwYXRtb3NwaGVyZXxlbnwxfHx8fDE3NjI3MjUwNDB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    backdropUrl: "https://images.unsplash.com/photo-1551536637-f5f1984f1398?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob3Jyb3IlMjBkYXJrJTIwYXRtb3NwaGVyZXxlbnwxfHx8fDE3NjI3MjUwNDB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    director: "Peter Jackson Jr.",
    cast: ["Eleanor Stone", "Gabriel Moore", "Isabella Cruz"],
    genres: ["Fantasy", "Adventure"],
    synopsis: "An epic journey through a magical realm where ancient prophecies and modern heroes collide in a battle for existence.",
    userRating: 4.6,
    criticScore: 88,
  },
];

export const mockReviews: Review[] = [
  {
    id: "1",
    movieId: "1",
    authorId: "u1",
    authorName: "Sarah Mitchell",
    isCritic: true,
    rating: 4.5,
    criticScore: 85,
    title: "A Stunning Achievement in Sci-Fi Cinema",
    content: "The Midnight Chronicles delivers a thought-provoking narrative that challenges our perception of time and freedom. Director Sarah Chen masterfully weaves together stunning visuals with deep philosophical questions.",
    spoilers: false,
    likes: 245,
    createdAt: "2024-11-08",
  },
  {
    id: "2",
    movieId: "1",
    authorId: "u2",
    authorName: "John Davis",
    isCritic: false,
    rating: 5,
    title: "Best Movie of the Year!",
    content: "Absolutely loved this film. The action sequences were incredible and the story kept me engaged throughout. Highly recommend!",
    spoilers: false,
    likes: 89,
    createdAt: "2024-11-09",
  },
];

export const mockLists: List[] = [
  {
    id: "1",
    name: "Top 250 Movies of All Time",
    description: "The definitive list of greatest films ever made, curated by our community.",
    coverUrl: mockMovies[0].posterUrl,
    itemCount: 250,
    isPublic: true,
    createdAt: "2024-01-01",
    movies: mockMovies.slice(0, 6),
  },
  {
    id: "2",
    name: "Must-Watch Sci-Fi",
    description: "Essential science fiction films that push the boundaries of imagination.",
    coverUrl: mockMovies[1].posterUrl,
    itemCount: 42,
    isPublic: true,
    createdAt: "2024-06-15",
    movies: mockMovies.slice(0, 3),
  },
];

export const mockReports: Report[] = [
  {
    id: "1",
    type: "spam",
    contentType: "review",
    contentId: "r123",
    contentPreview: "Check out my website for movie downloads! www.fake-site.com...",
    reporterId: "u456",
    reporterName: "John Smith",
    createdAt: "2024-11-09",
    status: "pending",
  },
  {
    id: "2",
    type: "offensive",
    contentType: "comment",
    contentId: "c789",
    contentPreview: "This is the worst movie ever made and anyone who likes it is...",
    reporterId: "u789",
    reporterName: "Jane Doe",
    createdAt: "2024-11-08",
    status: "pending",
  },
  {
    id: "3",
    type: "spoiler",
    contentType: "review",
    contentId: "r456",
    contentPreview: "The ending where the main character dies was so unexpected...",
    reporterId: "u321",
    reporterName: "Mike Johnson",
    createdAt: "2024-11-07",
    status: "pending",
  },
];

export const mockUser: UserProfile = {
  id: "u1",
  name: "Alex Turner",
  username: "alexturner",
  bio: "Film enthusiast and critic. Lover of sci-fi and indie cinema.",
  role: "critic",
  stats: {
    ratingsCount: 487,
    reviewsCount: 52,
    avgRating: 4.2,
    timeWatched: 1247,
  },
};

export const allGenres = [
  "Action",
  "Adventure",
  "Animation",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Fantasy",
  "Horror",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Thriller",
  "Western",
];
